### ISSUE TITLE
Github pages hosting is not properly set up

### ISSUE THREAD

**Issue by Rajat069** [Gunjan-Rajput/Calculator#1]

**Comment by Gunjan-Rajput** [comment]
You can solve this issue?

**Comment by Rajat069** [comment]
yes

**Comment by Gunjan-Rajput** [comment]
ok, u can.

**Comment by Rajat069** [comment]
you can follow any tutorial on youtube or you have to transfer me the ownership of your repo so that i will be able to host it correctly.

**Comment by Gunjan-Rajput** [comment]
https://github.com/Gunjan-Rajput/Calculator

**Comment by Gunjan-Rajput** [comment]
Ok, I have to transfer   the ownership of my repo  so you will be able to
host it correctly.

**Comment by Rajat069** [comment]
done

**Comment by Rajat069** [comment]
done
